# Generated by Django 6.0.7 on 2026-08-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCMS',
            fields=[
                ('id', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('homepage_sections', models.JSONField(blank=True, default=list)),
                ('hero_slides', models.JSONField(blank=True, default=list)),
                ('announcement_bar', models.JSONField(blank=True, default=dict)),
                ('brand_story', models.JSONField(blank=True, default=dict)),
                ('faq_items', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('store_name', models.CharField(default='Sansons', max_length=255)),
                ('support_email', models.EmailField(default='concierge@sansons.com', max_length=254)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('flat_shipping_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=10)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
