# Generated by Django 6.0.7 on 2026-08-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecms',
            name='featured_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitecms',
            name='featured_products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
