# Generated by Django 6.0.7 on 2026-08-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_visitoractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecms',
            name='footer_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_address',
            field=models.TextField(default='142 Atelier Street, New York, NY'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_phone',
            field=models.CharField(default='+1 (800) 555-0192', max_length=50),
        ),
    ]
