# Generated by Django 6.0.7 on 2026-08-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_sitecms_footer_content_sitesettings_store_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecms',
            name='hero_featured_products',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='return_policy_note',
            field=models.TextField(default='Please inspect package upon delivery. Returns accepted within 30 days.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipper_address',
            field=models.TextField(default='Sansons Warehouse, Industrial Hub Gate 4, Karachi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipper_email',
            field=models.EmailField(default='dispatch@sansons.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipper_name',
            field=models.CharField(default='Sansons Logistics & Fulfillment', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipper_phone',
            field=models.CharField(default='+92 300 1234567', max_length=50),
        ),
    ]
