# Generated by Django 6.0.7 on 2026-08-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_deleted_at_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='purchaser', max_length=50),
        ),
    ]
