# Generated by Django 6.0.7 on 2026-07-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_deleted_at_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deal_of_the_week',
            field=models.BooleanField(default=False),
        ),
    ]
