# Generated by Django 6.0.7 on 2026-08-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_banner_orderitem_item_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
